# ============================================================================
# AUTO-GENERATED by AgentKit v0.4.2
# ============================================================================
# Source: agentkit.yaml
# Checksum: sha256:e0c476561d9e3ba5
# ContentHash: sha256:ff44fb1b18eada04
# Generated: 2026-01-18T23:35:52.341307
# 
# This file is automatically generated and managed by AgentKit:
#   - It will be auto-updated when agentkit.yaml config changes (old version backed up)
#   - To fully customize, remove this header comment
#   - After removing the header, AgentKit will no longer manage this file
# 
# Force regenerate command:
#   agentkit build --regenerate-dockerfile
# 
# ============================================================================

# Support custom base image
FROM agentkit-cn-beijing.cr.volces.com/base/py-simple:python3.12-bookworm-slim-latest

ENV UV_SYSTEM_PYTHON=1 UV_COMPILE_BYTECODE=1 PYTHONUNBUFFERED=1 DOCKER_CONTAINER=1

COPY requirements.txt requirements.txt

RUN uv pip install -r requirements.txt

EXPOSE 8000

WORKDIR /app

# Copy entire project
COPY . .

CMD ["python", "-m", "tts_agentkit"]
